FROM node:24-alpine

WORKDIR /src

COPY src/package*.json ./

RUN npm ci --only=production

COPY src/ ./

RUN mkdir -p /src/db && chown -R node:node /src/db

EXPOSE 3000

USER node

CMD ["node", "main.js"]
