FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY src/ ./src/

RUN mkdir -p /src/db && chown -R node:node /src/db

EXPOSE 3000

USER node

CMD ["node", "src/main.js"]
